homepage:
    path:     /
    defaults: { _controller: SiteBundle:Site:index }
    options:
        expose: true

cartography:
    path:     /cartography
    defaults: { _controller: SiteBundle:Cartography:index }
    methods: [GET,POST]

homepage_vue:
    path:     /vue/
    defaults: { _controller: SiteBundle:Vue:index }

create_location:
    path:     /location/create
    defaults: { _controller: SiteBundle:Location:create }
    methods: POST
    options:
        expose: false

api_location_list:
    path:      /api/location/list
    defaults:  { _controller: SiteBundle:Cartography:list }
    methods: GET
    options:
        expose: true

api_sample:
    path:      /api/sample/{sample_id}
    defaults:  { _controller: SiteBundle:API\SampleApi:infos }
    methods: GET
    requirements:
        user_id: \d+
    options:
        expose: true

api_sample_update:
    path:      /api/sample/update/{sample_id}
    defaults:  { _controller: SiteBundle:API\SampleApi:update }
    methods: [POST, PUT, PATCH]
    requirements:
        user_id: \d+
    options:
        expose: true