homepage:
    path:     /
    defaults: { _controller: SiteBundle:Site:index }
    options:
        expose: true

cartography:
    path:     /cartography
    defaults: { _controller: SiteBundle:Cartography:index }
    methods: [GET,POST]
    options:
        expose: false

one_event:
    path:     /cartography/event/{event_id}
    defaults: { _controller: SiteBundle:Cartography:event }
    options:
        expose: true

homepage_vue:
    path:     /vue/
    defaults: { _controller: SiteBundle:Vue:index }

create_location:
    path:     /location/create
    defaults: { _controller: SiteBundle:Location:create }
    methods: POST
    options:
        expose: false

edit_location:
    path:     /location/edit/{location_id}
    defaults: { _controller: SiteBundle:Location:edit }
    options:
        expose: true

remove_location:
    path:     /location/remove/{location_id}
    defaults: { _controller: SiteBundle:Location:remove }
    options:
        expose: true

list_location:
    path:      /location/list
    defaults:  { _controller: SiteBundle:Location:list }
    options:
        expose: true


api_location_list:
    path:      /api/location/list
    defaults:  { _controller: SiteBundle:API\LocationApi:list }
    methods: GET
    options:
        expose: true

api_sample:
    path:      /api/sample/{sample_id}
    defaults:  { _controller: SiteBundle:API\SampleApi:infos }
    methods: GET
    requirements:
        user_id: \d+
    options:
        expose: true

api_sample_update:
    path:      /api/sample/update/{sample_id}
    defaults:  { _controller: SiteBundle:API\SampleApi:update }
    methods: [POST, PUT, PATCH]
    requirements:
        user_id: \d+
    options:
        expose: true