api_profile:
    path:      /api/profile/{user_id}
    defaults:  { _controller: UserBundle:API\UserApi:infos }
    requirements:
        user_id: \d+
    options:
        expose: true

api_user_logout:
    path:      /api/logout
    defaults:  { _controller: UserBundle:API\UserApi:logout }
    options:
        expose: true

api_user_usurpate:
    path:      /api/user/{user_id}/usurpate
    defaults:  { _controller: UserBundle:API\UserApi:usurpate }
    methods: GET
    requirements:
        user_id: \d+
    options:
        expose: true

api_profile_notify:
    path:      /api/profile/notify/{user_id}/
    defaults:  { _controller: UserBundle:API\UserApi:notifyAdmin }
    requirements:
        user_id: \d+
    options:
        expose: true

api_users_list:
    path:      /api/user/list
    defaults:  { _controller: UserBundle:API\UserApi:list }
    methods: GET
    options:
        expose: true

api_user_update:
    path:      /api/user/{user_id}/update
    defaults:  { _controller: UserBundle:API\UserApi:update }
    methods: [GET,PU,POST]
    requirements:
        user_id: \d+
    options:
        expose: true